apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      # Мониторинг node-exporter
      - job_name: 'node-exporter'
        static_configs:
        - targets: ['node-exporter:9100']  # Сервис node-exporter

      # Мониторинг вашего сервера
      - job_name: 'server'
        static_configs:
        - targets: ['server-service:8080']

      # Blackbox-проверки
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
        - targets:
          - server-service:8080
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter:9115
